<?php

if (!defined('CORE_VERSION'))
	die();


$core_fonts = array(__('Standard fonts', THEME_SLUG) =>
						array(	'Arial',
								'Arial Black',
								'Courier New',
								'Georgia',
								'Impact',
								'Times New Roman',
								'Trebuchet MS',
								'Verdana'),

					__('Google fonts', THEME_SLUG) =>
						array(	'Aclonica',
								'Aldrich',
								'Alice',
								'Allerta',
								'Amaranth',
								'Andika',
								'Anonymous Pro',
								'Antic', 
								'Anton',
								'Artifika',
								'Arvo',
								'Astloch',
								'Aubrey',
								'Bevan',
								'Black Ops One',
								'Bowlby One SC', 
								'Brawler',
								'Cabin',
								'Calligraffitti',
								'Candal',
								'Cardo',
								'Changa One',
								'Cherry Cream Soda', 
								'Comfortaa',
								'Crushed',
								'Cuprum',
								'Damion',
								'Delius',
								'Didact Gothic',
								'Droid Sans',
								'Droid Serif', 
								'Expletus Sans',
								'Fanwood Text',
								'Fontdiner Swanky',
								'Francois One',
								'Gentium Book Basic',
								'Geo', 
								'Goblin One',
								'Gruppo',
								'Irish Grover',
								'Josefin Slab',
								'Josefin Sans',
								'Julee',
								'Kranky', 
								'Lato',
								'Lekton',
								'Lobster',
								'Lobster Two',
								'Marvel',
								'Maven Pro',
								'Megrim',
								'Merienda One', 
								'Michroma',
								'Miltonian',
								'Monoton',
								'Montez',
								'Muli',
								'Neucha',
								'News Cycle',
								'Nobile',
								'Nothing You Could Do', 
								'Nova Square',
								'Numans',
								'Open Sans',
								'Orbitron',
								'Oswald',
								'Pacifico',
								'Paytone One',
								'Philosopher', 
								'Podkova',
								'Prociono',
								'PT Sans',
								'PT Serif',
								'Quattrocento Sans',
								'Redressed',
								'Rochester',
								'Rokkitt',
								'Rosario', 
								'Shanti',
								'Sigmar One',
								'Smythe',
								'Snippet',
								'Swanky and Moo Moo',
								'Syncopate',
								'Tangerine',
								'Tenor Sans', 
								'Terminal Dosis Light',
								'Tinos',
								'Ubuntu',
								'Unna',
								'Varela',
								'Volkhov',
								'Voltaire',
								'Wallpoet', 
								'Wire One',
								'Yanone Kaffeesatz')
					);

?>